safe: true
markdown: kramdown
permalink: /:title
relative_permalinks: false
sass:
  sass_dir: assets/stylesheets
gems:
  - jekyll-archives
  - jemoji
jekyll-archives:
  enabled: []
  layout: 'bootstrap'
  permalinks:
    year: 'blog/archive/:year/'
    month: 'blog/archive/:year/:month/'
    day: 'blog/archive/:year/:month/:day/'
    tag: 'blog/archive/tag/:name/'
    category: 'blog/archive/category/:name/'